dist: trusty
sudo: required

language: cpp

compiler:
  - gcc
  - clang

branches:
  only:
    - master
    - development
    - coverity_scan

before_install:
  - test $TRAVIS_BRANCH != coverity_scan -o ${TRAVIS_JOB_NUMBER##*.} = 1 || exit 0
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

script:
  - test $TRAVIS_BRANCH != coverity_scan || exit 0
  - mkdir build
  - cd build
  - cmake ..
  - make
  - chmod a+x binaries/run_tests.sh
  - ./binaries/run_tests.sh

env:
  global:
    - secure: "JFbvE2Q8uU5Rcooq369CzBmocjWlW3aQkdzLAWbk69S2TsuIRr3qXEnPOYqBkSXaa2yauVmDUb5E89txK5zn1TXUIZFqUh1zjFfvPsAaMbEJZTeQIJzZvWH4O6UjtG3or3v3ZXIpbUw5SEivWvRMnhbSz8o+d9lpKt8u6VC73Ws="

addons:
  coverity_scan:
    project:
      name: "siemens/embb"
    notification_email: tobias.schuele@siemens.com
    build_command_prepend: "mkdir build && cd build && cmake .. -DTHREADING_ANALYSIS_MODE=ON -DBUILD_TESTS=OFF"
    build_command: "make"
    branch_pattern: coverity_scan
